version: "3.9"

services:
  # 🧩 1️⃣ Datenbank
  frontend:
    build:
      context: .
      dockerfile: frontend.dockerfile
    container_name: stake_frontend
    ports:
      - "80:3001"
    env_file:
      - .env
    depends_on:
      - webserver
  db:
    build:
      context: .
      dockerfile: db.dockerfile
    container_name: stake_db
    env_file: .env.db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  # 💻 2️⃣ Node + Nuxt Webserver (Frontend)
  webserver:
    build:
      context: .
      dockerfile: webserver.dockerfile
    container_name: stake_web
    ports:
      - "3000:3003"
    depends_on:
      - db
    env_file:
      - .env
    restart: always

  # 🎲 3️⃣ Roulette-Microservice (Go)
  roulette:
    build:
      context: .
      dockerfile: microservices/roulette/Dockerfile
    container_name: roulette_service
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: always

volumes:
  db_data:
